config/routes.rb
Rails.application.routes.draw do
  resources :introductions
  resources :study_logs
  get 'friends/create'

  get 'friends/destroy'

  get 'friends/update'

  resources :goals
  resources :user_logs
  root 'static_pages#home'

  devise_for :users
  resources :friends, only: [:create, :destroy, :update]  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index]
  resources :tests, except: [:new, :create, :destroy]
    resources :categories do
      resources :tests, only: :create
      resources :words, only: [:index, :update]
    end
  

end

app/models/user_log.rb
class UserLog < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_logs_controller.rb
class UserLogsController < ApplicationController
  before_action :set_user_log, only: [:show]
  before_action :authenticate_user!
  # GET /user_logs
  # GET /user_logs.json
  def index
    # @user_logs = UserLog.all
    @user_logs = current_user.user_logs
  end

  # GET /user_logs/1
  # GET /user_logs/1.json
  def show
  end

  # GET /user_logs/new
  def new
    @user_log = UserLog.new
  end

  # GET /user_logs/1/edit
  def edit
  end

  # POST /user_logs
  # POST /user_logs.json
  def create
    @user_log = UserLog.new(user_log_params)

    respond_to do |format|
      if @user_log.save
        format.html { redirect_to @user_log, notice: 'User log was successfully created.' }
        format.json { render :show, status: :created, location: @user_log }
      else
        format.html { render :new }
        format.json { render json: @user_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_logs/1
  # PATCH/PUT /user_logs/1.json
  def update
    respond_to do |format|
      if @user_log.update(user_log_params)
        format.html { redirect_to @user_log, notice: 'User log was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_log }
      else
        format.html { render :edit }
        format.json { render json: @user_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_logs/1
  # DELETE /user_logs/1.json
  def destroy
    @user_log.destroy
    respond_to do |format|
      format.html { redirect_to user_logs_url, notice: 'User log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_log
      @user_log = UserLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_log_params
      params.require(:user_log).permit(:user_id, :log_data)
    end
end

app/views/user_logs/_form.html.erb
<%= form_for(@user_log) do |f| %>
  <% if @user_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_log.errors.count, "error") %> prohibited this user_log from being saved:</h2>

      <ul>
      <% @user_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :log_data %><br>
    <%= f.text_field :log_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_logs/edit.html.erb
<h1>Editing User Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_log %> |
<%= link_to 'Back', user_logs_path %>

app/views/user_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Logs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Log data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_logs.each do |user_log| %>
      <tr>
        <!--<td><%#= user_log.user_id %></td>-->
        <td><%= user_log.user.email %></td>
        <td><%= user_log.log_data %></td>
        <td><%= link_to 'Show', user_log %></td>
        <td><%= link_to 'Edit', edit_user_log_path(user_log) %></td>
        <td><%= link_to 'Destroy', user_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User log', new_user_log_path %>

app/views/user_logs/new.html.erb
<h1>New User Log</h1>

<%= render 'form' %>

<%= link_to 'Back', user_logs_path %>

app/views/user_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_log.user_id %>
</p>

<p>
  <strong>Log data:</strong>
  <%= @user_log.log_data %>
</p>

<%= link_to 'Edit', edit_user_log_path(@user_log) %> |
<%= link_to 'Back', user_logs_path %>