config/routes.rb
Rails.application.routes.draw do
  resources :introductions
  resources :study_logs
  get 'friends/create'

  get 'friends/destroy'

  get 'friends/update'

  resources :goals
  resources :user_logs
  root 'static_pages#home'

  devise_for :users
  resources :friends, only: [:create, :destroy, :update]  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index]
  resources :tests, except: [:new, :create, :destroy]
    resources :categories do
      resources :tests, only: :create
      resources :words, only: [:index, :update]
    end
  

end

app/models/study_log.rb
class StudyLog < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/controllers/study_logs_controller.rb
class StudyLogsController < ApplicationController
  before_action :set_study_log, only: [:show, :edit, :update, :destroy]

  # GET /study_logs
  # GET /study_logs.json
  def index
    #@study_logs = StudyLog.all
    @study_logs = current_user.study_logs.all
    #@groups_for_chart = @study_logs.to_a.group_by{|x| x.created_at.beginning_of_day}.map{|group| [group[0].strftime("%F"), group[1].map(&:learned_word).sum]}
    #@groups_for_chart = [[2015-11-06,20],[2015-11-05,25],[2015-11-03,10]]
    @groups_for_chart = [[2015-11-15,100],[2015-11-01,0]]
  end

  # GET /study_logs/1
  # GET /study_logs/1.json
  def show
  end

  # GET /study_logs/new
  def new
    @study_log = StudyLog.new
  end

  # GET /study_logs/1/edit
  def edit
  end

  # POST /study_logs
  # POST /study_logs.json
  def create
    @study_log = StudyLog.new(study_log_params)

    respond_to do |format|
      if @study_log.save
        format.html { redirect_to @study_log, notice: 'Study log was successfully created.' }
        format.json { render :show, status: :created, location: @study_log }
      else
        format.html { render :new }
        format.json { render json: @study_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /study_logs/1
  # PATCH/PUT /study_logs/1.json
  def update
    respond_to do |format|
      if @study_log.update(study_log_params)
        format.html { redirect_to @study_log, notice: 'Study log was successfully updated.' }
        format.json { render :show, status: :ok, location: @study_log }
      else
        format.html { render :edit }
        format.json { render json: @study_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study_logs/1
  # DELETE /study_logs/1.json
  def destroy
    @study_log.destroy
    respond_to do |format|
      format.html { redirect_to study_logs_url, notice: 'Study log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study_log
      @study_log = StudyLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_log_params
      params.require(:study_log).permit(:user_id, :learned_word)
    end
end

app/views/study_logs/_form.html.erb
<%= form_for(@study_log) do |f| %>
  <% if @study_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study_log.errors.count, "error") %> prohibited this study_log from being saved:</h2>

      <ul>
      <% @study_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :learned_word %><br>
    <%= f.number_field :learned_word %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/study_logs/_study_log.html.erb
<li id="study_log-<%= study_log.id %>">
  <%#= link_to gravatar_for(study_log.user, size: 50), study_log.user %>
  <img class="gravatar" src="https://cdn2.iconfinder.com/data/icons/my-cubicle/512/Notepad-512.png" style="width: 50px;height: 35px;">
  <span class="user">
    <b>動作</b>
      <%= study_log.content %>
  </span>
  <span class="content" style="">
      <b>日時</b>
      <%= study_log.created_at.strftime('%c') %>
  </span>
</li>

app/views/study_logs/edit.html.erb
<h1>Editing Study Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @study_log %> |
<%= link_to 'Back', study_logs_path %>

app/views/study_logs/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<%= column_chart @groups_for_chart %>

<%= line_chart @groups_for_chart %>




<p id="notice"><%= notice %></p>

<h1>Listing Study Logs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Learned word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @study_logs.each do |study_log| %>
      <tr>
        <td><%= study_log.user_id %></td>
        <td><%= study_log.learned_word %></td>
        <td><%= link_to 'Show', study_log %></td>
        <td><%= link_to 'Edit', edit_study_log_path(study_log) %></td>
        <td><%= link_to 'Destroy', study_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study log', new_study_log_path %>

app/views/study_logs/new.html.erb
<h1>New Study Log</h1>

<%= render 'form' %>

<%= link_to 'Back', study_logs_path %>

app/views/study_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @study_log.user_id %>
</p>

<p>
  <strong>Learned word:</strong>
  <%= @study_log.learned_word %>
</p>

<%= link_to 'Edit', edit_study_log_path(@study_log) %> |
<%= link_to 'Back', study_logs_path %>