config/routes.rb
Rails.application.routes.draw do
  resources :introductions
  resources :study_logs
  get 'friends/create'

  get 'friends/destroy'

  get 'friends/update'

  resources :goals
  resources :user_logs
  root 'static_pages#home'

  devise_for :users
  resources :friends, only: [:create, :destroy, :update]  
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index]
  resources :tests, except: [:new, :create, :destroy]
    resources :categories do
      resources :tests, only: :create
      resources :words, only: [:index, :update]
    end
  

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :average_score, presence: true
  validate :deadline_valid?

  belongs_to :user
  belongs_to :friend

  def deadline_valid?
    if deadline <= Time.zone.now
      errors.add(:deadline, "Deadline invalid!")
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /goals
  # GET /goals.json
  def index
    @goals = current_user.goals
    
    
    #current goal:
    @goal = current_user.goals.where("deadline > ?",Time.now).first
    #byebug
    if @goal != nil
      @tests = current_user.tests.where("mark >= 0 and created_at > ? and created_at < ?",@goal.created_at,@goal.deadline).order('created_at ASC')
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal = current_user.goals.where("deadline > ?",Time.now).first
    #byebug
    if @goal != nil
      @tests = current_user.tests.where("mark >= 0 and created_at > ? and created_at < ?",@goal.created_at,@goal.deadline).order('created_at ASC')
    end
  end

  # GET /goals/new
  def new
    @goal = Goal.new
    
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    @goal.current_average_score = 0.0
    @goal.current_test_done = 0
    @goal.test_cancelled = 0
    @user_logs = UserLog.new
    @user_logs.user_id = current_user.id
    @user_logs.log_data = "Creat new goal."
    @user_logs.save
    StudyLog.create(user_id: current_user.id,content: @goal.name+"という目標を作りました。")
    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: "Goal was successfully created." }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    @user_logs = UserLog.new
    @user_logs.user_id = current_user.id
    @user_logs.log_data = "Updated a goal."
    @user_logs.save
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: "Goal was successfully updated." }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @user_logs = UserLog.new
    @user_logs.user_id = current_user.id
    @user_logs.log_data = "Destroyed a goal."
    @user_logs.save
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: "Goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:name, :average_score, :deadline, :test_done)
    end
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>
      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "目標名" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "平均点数" %><br>
    <%= f.text_field :average_score %>
  </div>
  <div class="field">
    <%= f.label "やりたいテストの数量" %><br>
    <%= f.number_field :test_done %>
  </div>
  <div class="field">
    <%= f.label "締め切り" %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<div>
<%= link_to "編集", edit_goal_path(goal) %> |
<%= link_to "削除", goal, method: :delete, data: { confirm: "削除するか?" } %>
</div>

<div class="left-side sidebar-offcanvas">

<p id="notice"><%= notice %></p>



<p>
  <strong>目標名:</strong>
  <%= goal.name %>
</p>

<p>
  <strong>平均の点数:</strong>
  <%= goal.average_score %>
</p>

<p>
  <strong>やりたいテストの数:</strong>
  <%= goal.test_done %>
</p>
======================

<p>
  <strong>したテストの数:</strong>
  <%= goal.current_test_done %>
</p>

<p>
  <strong>取消したテストの数:</strong>
  <%= goal.test_cancelled %>
</p>

<p>
  <strong>開始日時:</strong>
  <% if goal.started_at == nil %>
    <td>Not started</td>
  <% else %>
    <td><%= goal.started_at %></td>
  <% end %>
</p>

<p>
  <strong>締め切り:</strong>
  <%= goal.deadline %>
</p>

<p>
  <strong>今の日時:</strong>
  <%= Time.zone.now %>
</p>

<p>
  <strong>残る期間:</strong>
  <% @days_left = goal.deadline - Time.zone.now %>
  <% if @days_left > 0 %>
   <%= @days_left.to_i / 86400  %> days
   <%#= Time.at(@days_left.to_i % 86400).utc.strftime("%H hours %M minutes") %>
   <%= Time.at(@days_left.to_i % 86400).utc.strftime("%H hours %M minutes") %>
  <% else %>
    目標が終わる
  <% end %>
</p>

</div>

<div class="right-side">
  
  <div class="description" >
  <div class="left">
  <div>平均の点数（目標）</div>
  <div class="heikin-tensuu"></div>    
  </div>
  <div class="left">
  <div>実際の点数</div>
  <div class="toreta-tensuu"></div>    
  </div>
  </div>
  
    <div class="box-header">
  <i class="fa fa-bar-chart-o"></i>
  <h4 class="box-title">点数</h4>
  </div>
  <div class="box-body">
      <div id="line-chart" style="height: 300px;"></div>
  </div><!-- /.box-body-->
  <div class="ox-name">テスト回目</div>
  </div>
</div>
        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script> 
        
        
        
        <script type="text/javascript">

            $(function() {
                /*
                 * LINE CHART
                 * ----------
                 */
                //LINE randomly generated data
                
                var data0 = [];
                for (var i = 1; i <= 30; i += 1) {
                  data0.push([i,0]);
                }

					 //var data0 = [[1.0,0],[1,1],[1,2],[1,3],[1,4],[1,5],[1,6],[1,7],[1,8],[1,9],[1,10],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0]];             
					 //var ox = [[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[<%= goal.test_done %>,0]];
					//var data1 = [[1,6],[2,8],[3,9],[4,5],[5,8],[6,9],[7,7]];
					var data1 = [];    
					<%  i = 0; %> 
					 <% @tests.each do |f| %>
					     <% i = i+1 %>;
					     data1.push([<%= i %>,<%= f.mark*0.5 %>]);
					 <% end %>
					 
					 //var data1 = [[1,6],[2,8],[3,9],[4,5],[5,8],[6,9],[7,7]];
					 //var data2 = [[1,6],[10,6]];
					 var data2 = [[1,<%= goal.average_score %>],[<%= goal.test_done %>,<%= goal.average_score %>]];
           
           var line_real_score = {
							data: data1,
                    color: "#3c8dbc"
                };
                
                var line_avarage_score = {
                    data: data2,
                    color: "red"
                };
                
                var scale = {
                    data: data0,
                    color: "white"
                };
                
                $.plot("#line-chart", [line_real_score,line_avarage_score,scale], {
                    grid: {
                        hoverable: true,
                        borderColor: "#f3f3f3",
                        borderWidth: 1,
                        tickColor: "#f3f3f3"
                    },
                    series: {
                        shadowSize: 0,
                        lines: {
                            show: true
                        },
                        points: {
                            show: true
                        }
                    },
                    lines: {
                        fill: false,
                        color: ["#3c8dbc", "#f56954"]
                    },
                    yaxis: {
                        show: true,
                    },
                    xaxis: {
                        show: true
                    }
                });
                //Initialize tooltip on hover
                $("<div class='tooltip-inner' id='line-chart-tooltip'></div>").css({
                    position: "absolute",
                    display: "none",
                    opacity: 0.8
                }).appendTo("body");
                
                $("#line-chart").bind("plothover", function(event, pos, item) {

                    if (item) {
                        var x = item.datapoint[0].toFixed(0),
                                y = item.datapoint[1].toFixed(1);

                        $("#line-chart-tooltip").html(x + "回目のテスト、点数： " + y)
                                .css({top: item.pageY + 5, left: item.pageX + 5})
                                .fadeIn(200);
                    } else {
                        $("#line-chart-tooltip").hide();
                    }

                });
                
                
                /* END LINE CHART */
            });

        </script>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render "form" %>

<%= link_to "Show", @goal %> |
<%= link_to "Back", goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<style >
  th,td{
    padding: 20px;
    text-align: center;
  }
  table{
    margin-left: 400px;
  }
</style>
<h1>今の目標</h1>
<h2><%= link_to "新しい目標を作る", new_goal_path, id: "search-form" %>  </h2>
<% if @goal != nil  %>
<%#= render @tests %>
<%#= @tests.count  %>
  <%= render @goals %>
<% else  %>
<h2>実行中の目標はまだありません。</h2><br>
<h2><%= link_to "新しい目標を作る", new_goal_path, id: "search-form" %>  </h2>
<% end  %>

<br>
<hr>
<br>
<h1>目標リスト</h1>

<table>
  <thead>
    <tr>
      <th>目標名</th>
      <th>平均の点数</th>
      <th>状況</th>
      <th>開始</th>
      <th>締め切り</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @goals.count != 0 %>
      <% @goals.each do |goal| %>
        <tr>
          <td><%= goal.name %></td>
          <td><%= goal.average_score %></td>
          <% if goal.deadline > Time.now %>
            <td>実行中</td>
          <% else %>
            <td>終わった</td>
          <% end %>
          <td><%= goal.created_at.strftime('%x') %></td>
          <td><%= goal.deadline.strftime('%x') %></td>
          <td><%= link_to "見る", goal %></td>
          <td><%= link_to "削除", goal, method: :delete, data: { confirm: "本当にしたいですか?" } %></td>
        </tr>
      <% end %>
    <% else %>
      <p> 目標の数量は０です。 </p>
    <% end %>  
  </tbody>
</table>

<br>

app/views/goals/new.html.erb
<h1>新しい勉強の目標</h1>

<div id="new_goal">
    <%= render "form" %>    
</div>


<%= link_to "Back", goals_path %>

app/views/goals/show.html.erb
<h1>目標管理</h1>
<div>
<%= link_to "Edit", edit_goal_path(@goal) %> |
<%= link_to "Back", goals_path %> |
<%= link_to "Destroy", @goal, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

<div class="left-side sidebar-offcanvas">

<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @goal.user_id %>
</p>

<p>
  <strong>Name of goal:</strong>
  <%= @goal.name %>
</p>

<p>
  <strong>Average score:</strong>
  <%= @goal.average_score %>
</p>

<p>
  <strong>Number of Test (Todo) :</strong>
  <%= @goal.test_done %>
</p>
======================
<p>
  <strong>Current Average score:</strong>
  <%= @goal.current_average_score %>
</p>

<p>
  <strong>Current Test done:</strong>
  <%= @goal.current_test_done %>
</p>

<p>
  <strong>Test cancelled:</strong>
  <%= @goal.test_cancelled %>
</p>

<p>
  <strong>Started at:</strong>
  <% if @goal.started_at == nil %>
    <td>Not started</td>
  <% else %>
    <td><%= @goal.started_at %></td>
  <% end %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @goal.deadline %>
</p>

<p>
  <strong>Time now:</strong>
  <%= Time.zone.now %>
</p>

<p>
  <strong>Days left:</strong>
  <% @days_left = @goal.deadline - Time.zone.now %>
  <% if @days_left > 0 %>
   <%= @days_left.to_i / 86400  %> days
   <%#= Time.at(@days_left.to_i % 86400).utc.strftime("%H hours %M minutes") %>
   <%= Time.at(@days_left.to_i % 86400).utc.strftime("%H hours %M minutes") %>
  <% else %>
    You missed this deadline.
  <% end %>
</p>

</div>

<div class="right-side">
  
  <div class="description" >
  <div class="left">
  <div>平均の点数（目標）</div>
  <div class="heikin-tensuu"></div>    
  </div>
  <div class="left">
  <div>実際の点数</div>
  <div class="toreta-tensuu"></div>    
  </div>
  </div>
  
    <div class="box-header">
  <i class="fa fa-bar-chart-o"></i>
  <h4 class="box-title">点数</h4>
  </div>
  <div class="box-body">
      <div id="line-chart" style="height: 300px;"></div>
  </div><!-- /.box-body-->
  <div class="ox-name">テスト回目</div>
  </div>
</div>
        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script> 
        
        
        
        <script type="text/javascript">

            $(function() {
                /*
                 * LINE CHART
                 * ----------
                 */
                //LINE randomly generated data
                
                var data0 = [];
                for (var i = 1; i <= 30; i += 1) {
                  data0.push([i,0]);
                }

					 //var data0 = [[1.0,0],[1,1],[1,2],[1,3],[1,4],[1,5],[1,6],[1,7],[1,8],[1,9],[1,10],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0]];             
					 //var ox = [[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[<%= @goal.test_done %>,0]];
					 var data1 = [[1,6],[2,8],[3,9],[4,5],[5,8],[6,9],[7,7]];
					 //var data2 = [[1,6],[10,6]];
					 var data2 = [[1,<%= @goal.average_score %>],[<%= @goal.test_done %>,<%= @goal.average_score %>]];
           
           var line_real_score = {
							data: data1,
                    color: "#3c8dbc"
                };
                
                var line_avarage_score = {
                    data: data2,
                    color: "red"
                };
                
                var scale = {
                    data: data0,
                    color: "white"
                };
                
                $.plot("#line-chart", [line_real_score,line_avarage_score,scale], {
                    grid: {
                        hoverable: true,
                        borderColor: "#f3f3f3",
                        borderWidth: 1,
                        tickColor: "#f3f3f3"
                    },
                    series: {
                        shadowSize: 0,
                        lines: {
                            show: true
                        },
                        points: {
                            show: true
                        }
                    },
                    lines: {
                        fill: false,
                        color: ["#3c8dbc", "#f56954"]
                    },
                    yaxis: {
                        show: true,
                    },
                    xaxis: {
                        show: true
                    }
                });
                //Initialize tooltip on hover
                $("<div class='tooltip-inner' id='line-chart-tooltip'></div>").css({
                    position: "absolute",
                    display: "none",
                    opacity: 0.8
                }).appendTo("body");
                
                $("#line-chart").bind("plothover", function(event, pos, item) {

                    if (item) {
                        var x = item.datapoint[0].toFixed(0),
                                y = item.datapoint[1].toFixed(1);

                        $("#line-chart-tooltip").html(x + "回目のテスト、点数： " + y)
                                .css({top: item.pageY + 5, left: item.pageX + 5})
                                .fadeIn(200);
                    } else {
                        $("#line-chart-tooltip").hide();
                    }

                });
                
                
                /* END LINE CHART */
            });

        </script>